<section class="section section-center section-cta">
    <div class="container">
        <iframe src="//player.vimeo.com/video/93695333?title=0&amp;byline=0&amp;portrait=0" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
    </div>
</section>

<?php foreach($this->sections as $section): ?>
    <?php
    $classes = [];
    if($section->getGroup('section.classes')){
        foreach($section->getGroup('section.classes')->getArray() as $item){
            $classes[] = $item->getText('class');
        }
    }
    $classes = implode(' ', $classes);
    ?>

    <section id="<?php echo $section->getSlug() ?>" class="section section-center section-cta <?php echo $classes;?>">
        <div class="container">
            <h2 class="section-title"><span><?php echo $section->getText('section.title')?></span></h2>
            <h2><?php echo $section->getText('section.subtitle')?></h2>
            <div class="row">
                <div class="col-lg-12">
                    <?php echo $section->getStructuredText('section.content')->asHtml() ?>
                </div>
            </div>

            <div class="main-action row">
                <div class="col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4">
                    <a href="/lvhack/register" class="smooth-scroll btn btn-lg btn-block btn-danger">Buy Tickets</a>
                </div>
            </div>
        </div>
    </section>
<?php endforeach; ?>


<section id="schedule" class="section section-center section-hilite section-pricing">
    <div class="container">
        <h2 class="section-title"><span>Schedule for #lvhack</span></h2>
        <div class="pricing-table">
            <div class="row">
                <?php foreach($schedule as $day): ?>
                    <div class="col-md-4 col-sm-6">
                        <div class="panel panel-primary">
                            <header class="panel-heading">
                                <h1><?php echo $day->getText('schedule.title') ?></h1>
                            </header>
                            <div class="panel-body">
                                <table class="table">
                                    <tbody>
                                    <?php foreach($day->getGroup('schedule.schedule')->getArray() as $item): ?>
                                        <tr class="<?php echo $this->cycle(["active", ""])->next()?>"><td><?php echo $item->getText('time') ?> - <?php echo $item->getText('title') ?></td></tr>
                                    <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</section>

<section id="sponsors" class="section">
    <div class="container">
        <div>
            <h2 class="section-title"><span>Sponsors</span></h2>
            <div class="row">
                <?php foreach($event->getGroup('event.sponsors')->getArray() as $sponsor): ?>
                    <div class="col-md-4 col-sm-12">
                        <img src="<?php echo $sponsor->getImage('logo')->getUrl(); ?>" style="margin-bottom: 30px"><br/>
                    </div>

                <?php endforeach; ?>
            </div>
        </div>
    </div>
</section>

