<!DOCTYPE html>
<html lang="en" ng-app>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>lvhack</title>
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <link rel="icon" href="favicon.ico" type="image/x-icon">
    <link href="/css/template.css" rel="stylesheet">
    <link href="/styles.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@lvtech">
    <meta name="twitter:creator" content="@lvtech">
    <meta name="twitter:title" content="#lvhack One amazing weekend to build exciting, interesting, and innovative things.">
    <meta name="twitter:description" content="#lvhack is the Lehigh Valley's first hackathon. For the past five years #lvhack has brought together great teams and great ideas. And quadcopters (aka, great prizes).">
    <meta name="twitter:image" content="http://<?php echo $_SERVER['HTTP_HOST'] ?>/images/lvhack-robot.png">


    <script type="text/javascript" src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap-3.1.1.min.js"></script>
    <script type="text/javascript" src="/js/jquery.isotope.min.js?v=1.5.26"></script>

    <?php echo $this->headScript(); ?>

    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-29148247-3', 'auto');
        ga('send', 'pageview');

    </script>
</head>

<body ng-controller="HackerStuff">
<div id="page">

<header id="header" class="site-header">
    <nav id="topbar" class="site-topbar visible-lg visible-md">
        <div class="container">
            <div class="row">
                <div class="col-sm-6"></div>
                <div class="social-links col-sm-6">
                    <a href="https://www.facebook.com/pages/Lehigh-Valley-Tech/117497908325262" target="_blank"><i class="fa fa-facebook"></i></a>
                    <a href="https://www.twitter.com/lvtech" target="_blank"><i class="fa fa-twitter"></i></a>
                    <a href="https://plus.google.com/u/0/106422994675607750950/posts" target="_blank"><i class="fa fa-google-plus"></i></a>
                </div>
            </div>
        </div>
    </nav>

    <nav id="navbar" class="site-navbar navbar navbar-static-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <i class="fa fa-bars"></i>
                </button>
                <h1 class="navbar-brand"><i class="fa fa-power-off"></i> <a href="/lvhack"><?php echo $this->event->getStructuredText('event.headline')->asHtml() ?></a></h1>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse-1">
                <ul id="navigation" class="nav navbar-nav navbar-right">
                    <?php if($this->event): ?>
                        <?php foreach($this->event->getGroup('event.sections')->getArray() as $section): ?>
                            <li><a href="/lvhack#<?php echo $this->escapeHtml($section['link']->getSlug()) ?>">
                                    <?php echo $this->escapeHtml(ucwords(str_replace('-', ' ', $section['link']->getSlug()))) ?>
                                </a></li>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <li class="active"><a href="/lvhack/register">Buy Tickets</a></li>
                    <li><a href="/lvhack#schedule">Schedule</a></li>
                    <li><a href="/lvhack#sponsors">Sponsors</a></li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<main id="main" class="site-main">

    <section id="carousel-1" class="carousel slide section-slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="item active" style="background: url(/images/featured_hack14.jpg) no-repeat;background-position: center top;
    background-size: 100% auto;background-color:#EC7A29;">
                <div class="container">
                    <img class="featured-robot" src="/images/lvhack-robot.png">
                </div>
            </div>

        </div>
    </section>

    <?php echo $this->content; ?>
</main>

<footer id="footer" class="site-footer">
    <div class="container">

        <div id="sidebar-footer-1">
            <div class="row">

                <aside class="widget col-md-12 col-sm-12">
                    <h5 class="widget-title">About The Organizers</h5>
                    <p>Lehigh Valley Tech is a local non-profit organization that promotes technology and entrepreneurship in the Lehigh Valley.
                        Our events are for start-ups, entrepreneurs, hackers, and technology enthusiasts in the Lehigh Valley to share and demo what they are working on.</p>
                </aside>


            </div>
        </div>


        <div class="copyright"><p>©2014 Lehigh Valley Tech, Inc.</p></div>
    </div>
</footer>
</div>

<div class="scroll-to-top" data-spy="affix" data-offset-top="200"><a href="#page" class="smooth-scroll"><i class="fa fa-arrow-up"></i></a></div>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-29148247-2', 'lehighvalleytech.org');
    ga('send', 'pageview');

</script>
</body>
</html>
