<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>Lehigh Valley Tech</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <meta name="geo.placename" content="Ben Franklin TechVentures, Bethlehem, PA">
    <meta name="geo.position" content="40.600140;-75.365669;" />

    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="css/themes/default/bootstrap.css" type="text/css">
    <link rel="stylesheet" href="css/themes/default/bootstrap-responsive.css" type="text/css">
    <link href="js/perfect-scrollbar-0.3.3/perfect-scrollbar.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="css/custom.css">

    <!--[if lt IE 9]>
    <link rel="stylesheet" href="css/bootstrap_ie7.css" type="text/css">
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <script src="http://maps.google.com/maps/api/js?sensor=false&libraries=places"></script>
    <script type="text/javascript" src="js/jquery.js"></script>
    <script type="text/javascript" src="js/jquery.mousewheel.js"></script>
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
    <script type="text/javascript" src="js/perfect-scrollbar-0.3.3/perfect-scrollbar.js"></script>
    <script type="text/javascript" src="js/global.js"></script>

    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-29148247-1', 'auto');
        ga('send', 'pageview');

    </script>

</head>

<body>

<div class="container-fluid">
    <div class="row-fluid main-row">
        <div class="span12 main-wrapper">

            <div class="row-fluid logo">
                <div class="span12">
                    <span class="logo_top"><img src="images/logo-lvtech.png"></span>
                </div>
            </div><!--/logo-->
            <?php echo $this->content ?>
            <div class="row-fluid leave-gap page-footer">
                <div class="span12">
                    <hr>
                    <div style="text-align: center;margin-bottom:10px;">
                        <ul class="social-icons">
                            <li><a href="http://twitter.com/lvtech"><i class="icon-twitter"></i></a></li>
                            <li><a href="https://www.facebook.com/pages/Lehigh-Valley-Tech/117497908325262?hc_location=timeline"><i class="icon-facebook"></i></a></li>
                            <li><a href="https://plus.google.com/106422994675607750950/posts"><i class="icon-google-plus"></i></a></li>
                            <li><a href="http://www.linkedin.com/company/lehigh-valley-tech?trk=top_nav_home"><i class="icon-linkedin"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div><!--/page-footer-->
        </div> <!-- end main-wrapper -->
    </div><!--/main-row-->
</div><!--/.container-fluid-->
</body>
</html>
