<div class="row-fluid block-wrapper">
    <div class="block" id="section-1">
        <div class="row-fluid">
            <div class="offset2 span8">
                <h2 style="font-size: 40px; line-height: 50px;">For start-ups, entrepreneurs, hackers, and technology enthusiasts in the Lehigh Valley to share and demo what they are working on.</h2>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12" >
                <h3>Our Monthly Meetups</h3>
                <p><strong><a href="http://meetup.org/lvtech">LVTech on Meetup.com</a></strong><br />
                    Social Meetup the 1st Tuesday of the Month<br />
                    and a Tech Meetup the 3rd Tuesday of the Month.
            </div>
        </div>
        <div class="row-fluid leave-gap">
            <div class="span12" >
                <h3>Our Annual Events
                    <p>
                        <strong><a href="/venture">Venture Lehigh Valley</a></strong><br>
                        <strong><a href="/lvhack">#lvhack (Lehigh Valley Hackathon)</a></strong>
                    </p>
            </div>
        </div>
        <div class="row-fluid leave-gap">
            <div class="span12" >
                <h3>LVTech Live</h3>
                <p>
                    <strong><a href="http://radio.lehighvalleytech.org">LVTech on YouTube (streams / recordings of meetups)</a></strong><br>
                    <strong><a href="http://radio.lehighvalleytech.org">LVTech Radio (live podcast)</a></strong><br>
                </p>
            </div>
        </div>
        <div class="row-fluid leave-gap">
            <div class="span12" >
                <h3>Contact Us</h3>
                <p>
                    <strong><a href="mailto:info@lehighvalleytech.org">info@lehighvalleytech.org</a></strong><br>
                </p>
            </div>
        </div>
    </div>
</div> <!-- end block-wrapper -->
