<?php
$ticket = $this->ticket;

$this->headScript()->appendFile('https://js.stripe.com/v2/');
$this->headScript()->captureStart();
?>
Stripe.setPublishableKey('<?php echo $this->stripe ?>');

jQuery(function($) {
    function stripeResponseHandler(status, response) {
        var $form = $('#payment-form');

        if (response.error) {
            $form.find('.payment-errors').text(response.error.message);
            $form.find('button').prop('disabled', false);
        } else {
            var token = response.id;
            $form.append($('<input type="hidden" name="stripeToken" />').val(token));
            $form.get(0).submit();
        }
    };

    $('#payment-form').submit(function(event) {
        var $form = $(this);
        $form.find('button').prop('disabled', true);
        Stripe.card.createToken($form, stripeResponseHandler);
        return false;
    });
});
<?php $this->headScript()->captureEnd(); ?>
<section class="">
    <div class="container-12">
        <h2>Payment</h2>
        <div class="row">
            <div class="grid-4">
                <div class="text-block-left">
                    <dl>
                        <dt>
                            Amount
                        </dt>
                        <dd>
                            $<?php echo $this->escapeHtml(substr($ticket['amount'], 0, strlen($ticket['amount']) - 2)) ?>
                        </dd>

                        <dt>
                            Type
                        </dt>
                        <dd>
                            <?php echo $this->ticket->type ?>
                        </dd>

                    </dl>
                </div>
            </div>
            <div class="grid-8">
                <div class="text-block-left">
                    <p class="subheading">Billing Information</p>

                    <p>
                        Complete your purchase with payment information.
                    </p>

                    <form action="" method="POST" id="payment-form">
                        <span class="payment-errors"></span>

                        <p>
                            <label>
                                <span>Email</span>
                                <input type="text" size="20" name="email" value="<?php echo $this->escapeHtml($ticket['email']) ?>"/>
                            </label>
                        </p>

                        <p>
                            <label>
                                <span>Name</span>
                                <input type="text" size="20" data-stripe="name" value="<?php echo $this->escapeHtml($ticket['name']) ?>"/>
                            </label>
                        </p>

                        <div class="form-row">
                            <label>
                                <span>Card Number</span>
                                <input type="text" size="20" data-stripe="number"/>
                            </label>
                        </div>

                        <div class="form-row">
                            <label>
                                <span>CVC</span>
                                <input type="text" size="4" data-stripe="cvc"/>
                            </label>
                        </div>

                        <div class="form-row">
                            <label>
                                <span>Expiration (MM/YYYY)</span>
                                <input type="text" size="2" data-stripe="exp-month"/>
                            </label>
                            <span> / </span>
                            <input type="text" size="4" data-stripe="exp-year"/>
                        </div>

                        <button type="submit">Submit Payment</button>
                    </form>

                </div>
            </div>
        </div>
        <div class="clear"></div>
    </div>
</section>
